import angular from 'angular';
import angular_ui_bootstrap from 'angular-ui-bootstrap';
import _ from 'lodash';

// Import our app config files
import constants  from './config/app.constants';
import appConfig  from './config/app.config';
import appRun     from './config/app.run';
import 'angular-ui-router';
import 'ngstorage';
// Import our templates file (generated by Gulp)
import './config/app.templates';
// Import our app functionaity
import './layout';
import './filters';
import './phrase';
import './services';

// Create and bootstrap application
const requires = [
  'ui.router',
  'templates',
  'ngStorage',
  'ui.bootstrap',
  'app.layout',
  'app.filters',
  'app.services',
  'app.phrase'
];

window._ = _;
// Mount on window for testing
window.app = angular.module('app', requires);

angular.module('app').constant('AppConstants', constants);

angular.module('app').constant('_', _);

angular.module('app').run(appRun);

angular.module('app').config(appConfig);

//angular.module('app').run(appRun);

angular.bootstrap(document, ['app'], {
  strictDi: true
});